name: custom_lint_visitor
version: 1.0.0+8.1.1
description: A package that exports visitors for CustomLint.
repository: https://github.com/invertase/dart_custom_lint

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: 8.1.1

dev_dependencies:
  build_runner: ^2.5.0
  lint_visitor_generator:
    path: ../lint_visitor_generator
  test: ^1.22.2
